# Make a service out of the Dockerfile in /book_api
services:
  chroma_db:
    image: chromadb/chroma
    expose:
      - "8000"  # Document Chroma port
    volumes:
      - ./book_api/chroma_db:/data/
  book_api:
    build:
      context: .
      dockerfile: book_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./book_api/persistence.db:/app/book_api/persistence.db
    environment:
      - CHROMA_HOST=chroma_db
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - chroma_db
  book_ui:
    build:
      context: .
      dockerfile: book_ui/Dockerfile
    ports:
      - 80:80
    depends_on:
      - book_api